### PR TITLE
fix for files playing with incorrect mediatype

### PR DESCRIPTION
**Pull request by henryjfry**
Foxystreams seems to not apply the mediatype correctly from "ui.metadata_from(args)" so I added a manual check to apply it should it not get picked up correctly.

### CODE REVIEW

**Comment by ruinernin** [comment]
Thanks for the PR.

Do you know why the infolabel type needs to be set to `videos` instead of `video` in the case of `mediatype`? I've not seen any reference to `videos` as type in the [documentation](https://codedocs.xyz/xbmc/xbmc/group__python__xbmcgui__listitem.html#ga0b71166869bda87ad744942888fb5f14).

**Comment by drinfernoo** [comment]
I've noticed in various adjacent API docs, or similar, inconsistencies between plural and singular (`movie` vs `movies`, etc), but I didn't realize we had to worry about that in Kodi docs, too 😩

Just par for the course, I guess!

**Comment by henryjfry** [comment]
Yeah there seem to be video infolabels and videos infolabels, I hadn't actually noticed that before but that could explain some issues I've had in the past.

**Comment by ruinernin** [comment]
Thanks again for the PR and for the explination!

**Pull request merged**
